package com.lef.frame.dal.entity;

import java.util.Date;

public class AsynNoticeInfo  extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASYN_NOTICE_INFO.ID
     *
     * @mbggenerated
     */
    private Long id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASYN_NOTICE_INFO.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASYN_NOTICE_INFO.SEND_STATUS
     *
     * @mbggenerated
     */
    private String sendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASYN_NOTICE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASYN_NOTICE_INFO.SEND_TIME
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASYN_NOTICE_INFO.BIZ_NO
     *
     * @mbggenerated
     */
    private String bizNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASYN_NOTICE_INFO.ID
     *
     * @return the value of ASYN_NOTICE_INFO.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASYN_NOTICE_INFO.ID
     *
     * @param id the value for ASYN_NOTICE_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASYN_NOTICE_INFO.CONTENT
     *
     * @return the value of ASYN_NOTICE_INFO.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASYN_NOTICE_INFO.CONTENT
     *
     * @param content the value for ASYN_NOTICE_INFO.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASYN_NOTICE_INFO.SEND_STATUS
     *
     * @return the value of ASYN_NOTICE_INFO.SEND_STATUS
     *
     * @mbggenerated
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASYN_NOTICE_INFO.SEND_STATUS
     *
     * @param sendStatus the value for ASYN_NOTICE_INFO.SEND_STATUS
     *
     * @mbggenerated
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASYN_NOTICE_INFO.CREATE_TIME
     *
     * @return the value of ASYN_NOTICE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public Object getCreateTime() {
        return createTime;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASYN_NOTICE_INFO.SEND_TIME
     *
     * @return the value of ASYN_NOTICE_INFO.SEND_TIME
     *
     * @mbggenerated
     */
    public Object getSendTime() {
        return sendTime;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASYN_NOTICE_INFO.BIZ_NO
     *
     * @return the value of ASYN_NOTICE_INFO.BIZ_NO
     *
     * @mbggenerated
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASYN_NOTICE_INFO.BIZ_NO
     *
     * @param bizNo the value for ASYN_NOTICE_INFO.BIZ_NO
     *
     * @mbggenerated
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
}