package com.lef.frame.dal.mappers;

import com.lef.frame.dal.entity.AsynNoticeInfo;
import java.util.List;

public interface AsynNoticeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASYN_NOTICE_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASYN_NOTICE_INFO
     *
     * @mbggenerated
     */
    int insert(AsynNoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASYN_NOTICE_INFO
     *
     * @mbggenerated
     */
    AsynNoticeInfo selectByPrimaryKey(Long id);
    
    AsynNoticeInfo selectByBizNo(String bizNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASYN_NOTICE_INFO
     *
     * @mbggenerated
     */
    List<AsynNoticeInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASYN_NOTICE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AsynNoticeInfo record);
}