package com.lef.frame.dal.mappers;

import com.lef.frame.dal.entity.OrderInfo;
import java.math.BigDecimal;
import java.util.List;

public interface OrderInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORDER_INFO
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORDER_INFO
	 * @mbggenerated
	 */
	int insert(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORDER_INFO
	 * @mbggenerated
	 */
	OrderInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORDER_INFO
	 * @mbggenerated
	 */
	List<OrderInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORDER_INFO
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderInfo record);
}