package com.lef.frame.dal.mappers;

import com.lef.frame.dal.entity.PaymentInfo;
import java.math.BigDecimal;
import java.util.List;

public interface PaymentInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PAYMENT_INFO
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PAYMENT_INFO
	 * @mbggenerated
	 */
	int insert(PaymentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PAYMENT_INFO
	 * @mbggenerated
	 */
	PaymentInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PAYMENT_INFO
	 * @mbggenerated
	 */
	List<PaymentInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PAYMENT_INFO
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PaymentInfo record);
}